var json={
    "name": "三餐好味",
    "logo": "/img/logo.jpg",
    "lunbo":[
      "/img/lunbo1.jpg",
      "/img/lunbo2.jpg",
      "/img/lunbo3.jpg"
    ],
    "layer":[
      {"url":"/img/pro1.jpg","kind":"早餐","count":"56种"},
      {"url":"/img/pro2.jpg","kind":"宝宝辅食","count":"43种"},
      {"url":"/img/pro3.jpg","kind":"烘培","count":"87种"},
      {"url":"/img/pro4.jpg","kind":"食疗养生","count":"33种"}
    ],
    "pic_list":[
      "/img/pic1.jpg",
      "/img/pic2.jpg",
      "/img/pic3.jpg",
      "/img/pic4.jpg",
      "/img/pic5.jpg",
      "/img/pic6.jpg",
      "/img/pic7.jpg",
      "/img/pic8.jpg"
    ],
    "footer":[
      "如果你不知道吃什么，那就来找我吧！",
      "三餐好味客服中心设立在黑龙江省哈尔滨市",
      "客服电话：13423313908 随时恭候您！"
    ],
    "resource":[
            {
              "url":"/img/layer1.jpg",
              "title":"鲁菜--四喜丸子",
              "feature":"颜色金黄，咸鲜酥嫩，芡汁清亮，味道适口",
              "desc":"由四个色泽金黄、香味四溢、形态栩栩如生的丸子组成，寓意人生福、禄、寿、喜。"
            },
            {
              "url":"/img/layer2.jpg",
              "title":"东北菜--锅包肉",
              "feature":"外观红白相同，肉质外焦里嫩，微酸微甜",
              "desc":"原名锅爆肉，光绪年间始创自哈尔滨道台府府尹杜学赢厨师郑兴文之手。"
            },
            {
              "url":"/img/layer3.jpg",
              "title":"川菜--水煮鱼",
              "feature":"油而不腻，辣而不燥，麻而不苦，肉质滑嫩",
              "desc":"水煮鱼也称江水煮江鱼、水煮鱼片，最早流行于重庆市渝北区翠云乡。"
            }
          ]  ,
      user:[
        {name:"aaa",password:"111"},
        {name:"bbb",password:"222"},
        {name:"ccc",password:"333"},
      ],
      "breakfast":[
        {
          "url":"/img/work1.jpg",
          "title":"番茄火腿酸汤面",
          "desc":"酸爽开胃，浓浓汤汁裹满面超级好吃"
        },
        {
          "url":"/img/work2.jpg",
          "title":"香蕉烤燕麦",
          "desc":"健康且营养均衡的低脂早餐"
        },
        {
          "url":"/img/work3.jpg",
          "title":"迷你菜蟒",
          "desc":"减肥迷你菜蟒，越吃越瘦的早餐"
        },
        {
          "url":"/img/work4.jpg",
          "title":"蛋黄酱三明治",
          "desc":"料超多，一口下去超满足"
        },
        {
          "url":"/img/work5.jpg",
          "title":"日式厚蛋烧",
          "desc":"蛋香超浓郁，口感嫩滑"
        },
        {
          "url":"/img/work6.jpg",
          "title":"西兰花虾仁豆腐蒸蛋",
          "desc":"鸡蛋羹超滑嫩，大粒的虾仁，超好吃"
        },
        {
          "url":"/img/work7.jpg",
          "title":"青菜香菇粥",
          "desc":"咕噜咕噜喝下一口，既暖胃又暖心"
        },
        {
          "url":"/img/work8.jpg",
          "title":"鲜虾时蔬粥",
          "desc":"甜鲜绵滑，香滑浓稠，巨好喝"
        },
      ]
  }

module.exports={
  dataList:json
}